apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: currency-conversion
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
      - image: drmodi/currency-conversion:3.0.0-RELEASE #CHANGE
        imagePullPolicy: Always
        name: currency-conversion
        env:   #CHANGE
        - name: JAEGER_SERVICE_NAME
          value: currency-conversion   #CHANGE 
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent.istio-system.svc.cluster.local
        - name: JAEGER_REPORTER_LOG_SPANS
          value: "true"
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_PROPAGATION
          value: b3        
        - name: CURRENCY_EXCHANGE_URI
          value: http://currency-exchange:8000

      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: currency-conversion
  name: currency-conversion
  namespace: default
spec:
  ports:
  - # nodePort: 30701
    port: 8100
    protocol: TCP
    targetPort: 8100 
  selector:
    app: currency-conversion
  sessionAffinity: None
  #type: LoadBalancer